<a href="https://colab.research.google.com/github/sindhura-nk/Machine-Learning-1491/blob/main/K_Means_Clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## K-Means Clustering

## Build a model that creates customer groups who are frequently visiting the mall on basis of Age,Income and Spending

In [1]:
path = r'https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/Mall_Customers.csv'
import pandas as pd
df = pd.read_csv(path)
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

## Perform basic data quality checks

In [2]:
df.shape

(200, 5)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    str
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), str(1)
memory usage: 7.9 KB

In [3]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='str')

In [4]:
## Duplicated rows
df.duplicated().sum()

np.int64(0)

In [5]:
df=df.drop_duplicates()

In [6]:
# Missing values
df.isna().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

## Separate X features. Consider the features for which you want clusters to be formed.
You can perform EDA to decide which features to consider for cluster creation

In [7]:
X = df.drop(columns=['Gender','CustomerID'])
X.head()

   Age  Annual Income (k$)  Spending Score (1-100)
0   19                  15                      39
1   21                  15                      81
2   20                  16                       6
3   23                  16                      77
4   31                  17                      40

In [8]:
X.columns = ['Age','Income','Spending']
X.columns

Index(['Age', 'Income', 'Spending'], dtype='str')

## Data Cleaning and Preprocessing

In [9]:
X.dtypes

Age         int64
Income      int64
Spending    int64
dtype: object

In [10]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

num_pipe = make_pipeline(
    SimpleImputer(strategy='median'),
    StandardScaler()
).set_output(transform='pandas')

X_pre = num_pipe.fit_transform(X)
X_pre.head()

        Age    Income  Spending
0 -1.424569 -1.738999 -0.434801
1 -1.281035 -1.738999  1.195704
2 -1.352802 -1.700830 -1.715913
3 -1.137502 -1.700830  1.040418
4 -0.563369 -1.662660 -0.395980

## Model Building

In [11]:
pip install yellowbrick

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: yellowbrick in c:\users\archa\appdata\roaming\python\python312\site-packages (1.5)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.2 in c:\users\archa\appdata\roaming\python\python312\site-packages (from yellowbrick) (3.10.8)
Requirement already satisfied: scipy>=1.0.0 in c:\users\archa\appdata\roaming\python\python312\site-packages (from yellowbrick) (1.17.0)
Requirement already satisfied: scikit-learn>=1.0.0 in c:\users\archa\appdata\roaming\python\python312\site-packages (from yellowbrick) (1.8.0)
Requirement already satisfied: numpy>=1.16.0 in c:\users\archa\appdata\roaming\python\python312\site-packages (from yellowbrick) (2.4.2)
Requirement already satisfied: cycler>=0.10.0 in c:\users\archa\appdata\roaming\python\python312\site-packages (from yellowbrick) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\archa\appdata\roaming\python\python312\site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.3.3)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\archa\appdata\roaming\python\python312\site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\archa\appdata\roaming\python\python312\site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\archa\appdata\roaming\python\python312\site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\archa\appdata\roaming\python\python312\site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\archa\appdata\roaming\python\python312\site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\archa\appdata\roaming\python\python312\site-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (2.9.0.post0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\archa\appdata\roaming\python\python312\site-packages (from scikit-learn>=1.0.0->yellowbrick) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\archa\appdata\roaming\python\python312\site-packages (from scikit-learn>=1.0.0->yellowbrick) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\archa\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
from sklearn.cluster import KMeans
from yellowbrick.cluster import kelbow_visualizer

ModuleNotFoundError: No module named 'distutils'

In [13]:
import matplotlib.pyplot as plt

base_model = KMeans()
visualizer = kelbow_visualizer(base_model,X_pre,k=(2,11),timings=False)
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
visualizer.show()

NameError: name 'kelbow_visualizer' is not defined

In [14]:
## Build the model with K=6
final_model = KMeans(n_clusters=6) # k=n_clusters
clusters = final_model.fit_predict(X_pre) # cluster creation : 6 clusters , cluster information for each datapoint
clusters

array([5, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5,
       2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 0, 5, 2, 5,
       2, 5, 0, 4, 4, 4, 0, 4, 4, 0, 0, 0, 0, 0, 4, 0, 0, 4, 0, 0, 0, 4,
       0, 0, 4, 4, 0, 0, 0, 0, 0, 4, 0, 4, 4, 0, 0, 4, 0, 0, 4, 0, 0, 4,
       4, 0, 0, 4, 0, 4, 4, 4, 0, 4, 0, 4, 4, 0, 0, 4, 0, 4, 0, 0, 0, 0,
       0, 4, 4, 4, 4, 4, 0, 0, 0, 0, 4, 4, 4, 1, 4, 1, 3, 1, 3, 1, 3, 1,
       4, 1, 4, 1, 3, 1, 4, 1, 3, 1, 4, 1, 4, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1, 3, 1, 3, 1, 0, 1, 4, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1], dtype=int32)

In [15]:
final_model.cluster_centers_

array([[ 1.25472096, -0.24021294, -0.04399777],
       [-0.44191719,  0.99158305,  1.23950275],
       [ 0.47895722, -1.30822992, -1.19644353],
       [ 0.36959845,  1.12879725, -1.25264236],
       [-0.90119708, -0.05954431, -0.20850019],
       [-0.97602698, -1.32549704,  1.0371827 ]])

In [16]:
X.head()

   Age  Income  Spending
0   19      15        39
1   21      15        81
2   20      16         6
3   23      16        77
4   31      17        40

In [17]:
X['Customer_Groups'] = clusters
X.head()

   Age  Income  Spending  Customer_Groups
0   19      15        39                5
1   21      15        81                5
2   20      16         6                2
3   23      16        77                5
4   31      17        40                2

In [18]:
fil1 = X['Customer_Groups']==0
X[fil1]

     Age  Income  Spending  Customer_Groups
40    65      38        35                0
46    50      40        55                0
50    49      42        52                0
53    59      43        60                0
54    50      43        45                0
55    47      43        41                0
56    51      44        50                0
57    69      44        46                0
59    53      46        46                0
60    70      46        56                0
62    67      47        52                0
63    54      47        59                0
64    63      48        51                0
66    43      48        50                0
67    68      48        48                0
70    70      49        55                0
71    47      49        42                0
72    60      50        49                0
73    60      50        56                0
74    59      54        47                0
76    45      54        53                0
79    49      54        42                0
80    57      54        51                0
82    67      54        41                0
83    46      54        44                0
85    48      54        46                0
86    55      57        58                0
89    50      58        46                0
90    68      59        55                0
92    48      60        49                0
96    47      60        47                0
98    48      61        42                0
101   49      62        48                0
102   67      62        59                0
104   49      62        56                0
106   66      63        50                0
107   54      63        46                0
108   68      63        43                0
109   66      63        48                0
110   65      63        52                0
116   63      65        43                0
117   49      65        59                0
118   51      67        43                0
119   50      67        57                0
160   56      79        35                0

In [24]:
for i in range(6):
  print(f'Cluster {i}')
  display(X[X['Customer_Groups']==i])
  print("===============")

Cluster 0

     Age  Income  Spending  Customer_Groups
40    65      38        35                0
46    50      40        55                0
50    49      42        52                0
53    59      43        60                0
54    50      43        45                0
55    47      43        41                0
56    51      44        50                0
57    69      44        46                0
59    53      46        46                0
60    70      46        56                0
62    67      47        52                0
63    54      47        59                0
64    63      48        51                0
66    43      48        50                0
67    68      48        48                0
70    70      49        55                0
71    47      49        42                0
72    60      50        49                0
73    60      50        56                0
74    59      54        47                0
76    45      54        53                0
79    49      54        42                0
80    57      54        51                0
82    67      54        41                0
83    46      54        44                0
85    48      54        46                0
86    55      57        58                0
89    50      58        46                0
90    68      59        55                0
92    48      60        49                0
96    47      60        47                0
98    48      61        42                0
101   49      62        48                0
102   67      62        59                0
104   49      62        56                0
106   66      63        50                0
107   54      63        46                0
108   68      63        43                0
109   66      63        48                0
110   65      63        52                0
116   63      65        43                0
117   49      65        59                0
118   51      67        43                0
119   50      67        57                0
160   56      79        35                0

===============
Cluster 1

     Age  Income  Spending  Customer_Groups
123   39      69        91                1
125   31      70        77                1
127   40      71        95                1
129   38      71        75                1
131   39      71        75                1
133   31      72        71                1
135   29      73        88                1
137   32      73        73                1
139   35      74        72                1
141   32      75        93                1
143   32      76        87                1
145   28      77        97                1
147   32      77        74                1
149   34      78        90                1
151   39      78        88                1
153   38      78        76                1
155   27      78        89                1
157   30      78        78                1
159   30      78        73                1
161   29      79        83                1
163   31      81        93                1
165   36      85        75                1
167   33      86        95                1
169   32      87        63                1
171   28      87        75                1
173   36      87        92                1
175   30      88        86                1
177   27      88        69                1
179   35      93        90                1
181   32      97        86                1
183   29      98        88                1
185   30      99        97                1
187   28     101        68                1
189   36     103        85                1
191   32     103        69                1
193   38     113        91                1
195   35     120        79                1
197   32     126        74                1
199   30     137        83                1

===============
Cluster 2

    Age  Income  Spending  Customer_Groups
2    20      16         6                2
4    31      17        40                2
6    35      18         6                2
8    64      19         3                2
10   67      19        14                2
12   58      20        15                2
14   37      20        13                2
16   35      21        35                2
18   52      23        29                2
20   35      24        35                2
22   46      25         5                2
24   54      28        14                2
26   45      28        32                2
28   40      29        31                2
30   60      30         4                2
32   53      33         4                2
34   49      33        14                2
36   42      34        17                2
38   36      37        26                2
42   48      39        36                2
44   49      39        28                2

===============
Cluster 3

     Age  Income  Spending  Customer_Groups
126   43      71        35                3
128   59      71        11                3
130   47      71         9                3
136   44      73         7                3
140   57      75         5                3
146   48      77        36                3
148   34      78        22                3
150   43      78        17                3
152   44      78        20                3
154   47      78        16                3
156   37      78         1                3
158   34      78         1                3
164   50      85        26                3
166   42      86        20                3
168   36      87        27                3
170   40      87        13                3
172   36      87        10                3
174   52      88        13                3
176   58      88        15                3
178   59      93        14                3
180   37      97        32                3
182   46      98        15                3
184   41      99        39                3
186   54     101        24                3
188   41     103        17                3
190   34     103        23                3
192   33     113         8                3
194   47     120        16                3
196   45     126        28                3
198   32     137        18                3

===============
Cluster 4

     Age  Income  Spending  Customer_Groups
47    27      40        47                4
48    29      40        42                4
49    31      40        42                4
51    33      42        60                4
52    31      43        54                4
58    27      46        51                4
61    19      46        55                4
65    18      48        59                4
68    19      48        59                4
69    32      48        47                4
75    26      54        54                4
77    40      54        48                4
78    23      54        52                4
81    38      54        55                4
84    21      54        57                4
87    22      57        55                4
88    34      58        60                4
91    18      59        41                4
93    40      60        40                4
94    32      60        42                4
95    24      60        52                4
97    27      60        50                4
99    20      61        49                4
100   23      62        41                4
103   26      62        55                4
105   21      62        42                4
111   19      63        54                4
112   38      64        42                4
113   19      64        46                4
114   18      65        48                4
115   19      65        50                4
120   27      67        56                4
121   38      67        40                4
122   40      69        58                4
124   23      70        29                4
132   25      72        34                4
134   20      73         5                4
138   19      74        10                4
142   28      76        40                4
144   25      77        12                4
162   19      81         5                4

===============
Cluster 5

    Age  Income  Spending  Customer_Groups
0    19      15        39                5
1    21      15        81                5
3    23      16        77                5
5    22      17        76                5
7    23      18        94                5
9    30      19        72                5
11   35      19        99                5
13   24      20        77                5
15   22      20        79                5
17   20      21        66                5
19   35      23        98                5
21   25      24        73                5
23   31      25        73                5
25   29      28        82                5
27   35      28        61                5
29   23      29        87                5
31   21      30        73                5
33   18      33        92                5
35   21      33        81                5
37   30      34        73                5
39   20      37        75                5
41   24      38        92                5
43   31      39        61                5
45   24      39        65                5

===============

## Clusters- Visualization

In [20]:
X.columns

Index(['Age', 'Income', 'Spending', 'Customer_Groups'], dtype='str')

In [23]:
import plotly.express as ex
fig = ex.scatter_3d(X,x='Age',y='Income',z='Spending',color='Customer_Groups')
fig.show()

ModuleNotFoundError: No module named 'plotly'

## Save the X file

In [22]:
X.to_csv("Mall_Customer_Groups.csv",index=False)

## Assignment:
1) Perform the above steps considering features Gender and Spending
2) Perform the above steps considering all the features except customer ID.