Project: 1 Regression

Name: Mayuri Sangade

Delivery Duration Prediction

Build a linear Regression Model to predict the estimated time taken for a delivery

Step 1: Load Dataset

In [5]:
import pandas as pd
path = r"E:\Mayuri\DataSets\historical_data.csv"
#Load data
df = pd.read_csv(path)
#preview data
df.head()

,market_id,created_at,actual_delivery_time,store_id,store_primary_category,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration
0,1.0,22:24:17,23:27:16,1845,american,1.0,4,3441,4,557,1239,33.0,14.0,21.0,446,861.0
1,2.0,21:49:25,22:56:29,5477,mexican,2.0,1,1900,1,1400,1400,1.0,2.0,2.0,446,690.0
2,3.0,20:39:28,21:09:09,5477,NaN,1.0,1,1900,1,1900,1900,1.0,0.0,0.0,446,690.0
3,3.0,21:21:45,22:13:00,5477,NaN,1.0,6,6900,5,600,1800,1.0,1.0,2.0,446,289.0
4,3.0,02:40:36,03:20:26,5477,NaN,1.0,3,3900,3,1100,1600,6.0,6.0,9.0,446,650.0

Step 2: perform basic data quality check

In [6]:
df.shape

(197428, 16)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 197428 entries, 0 to 197427
Data columns (total 16 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   market_id                                     196441 non-null  float64
 1   created_at                                    197428 non-null  str
 2   actual_delivery_time                          197421 non-null  str
 3   store_id                                      197428 non-null  int64
 4   store_primary_category                        192668 non-null  str
 5   order_protocol                                196433 non-null  float64
 6   total_items                                   197428 non-null  int64
 7   subtotal                                      197428 non-null  int64
 8   num_distinct_items                            197428 non-null  int64
 9   min_item_price                                197428 non-null  int64
 10  max_item_price                                197428 non-null  int64
 11  total_onshift_dashers                         181166 non-null  float64
 12  total_busy_dashers                            181166 non-null  float64
 13  total_outstanding_orders                      181166 non-null  float64
 14  estimated_order_place_duration                197428 non-null  int64
 15  estimated_store_to_consumer_driving_duration  196902 non-null  float64
dtypes: float64(6), int64(7), str(3)
memory usage: 24.1 MB

Step 3: Converted Time Columns

**Converted time columns like created_at & actual_delivery_time from string to datetime format**

In [8]:
df['created_at'] = pd.to_datetime(df['created_at'])
df['actual_delivery_time'] = pd.to_datetime(df['actual_delivery_time'])

C:\Users\archa\AppData\Local\Temp\ipykernel_25656\2394805760.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['created_at'] = pd.to_datetime(df['created_at'])
C:\Users\archa\AppData\Local\Temp\ipykernel_25656\2394805760.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['actual_delivery_time'] = pd.to_datetime(df['actual_delivery_time'])

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 197428 entries, 0 to 197427
Data columns (total 16 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   market_id                                     196441 non-null  float64
 1   created_at                                    197428 non-null  datetime64[us]
 2   actual_delivery_time                          197421 non-null  datetime64[us]
 3   store_id                                      197428 non-null  int64
 4   store_primary_category                        192668 non-null  str
 5   order_protocol                                196433 non-null  float64
 6   total_items                                   197428 non-null  int64
 7   subtotal                                      197428 non-null  int64
 8   num_distinct_items                            197428 non-null  int64
 9   min_item_price                                197428 non-null  int64
 10  max_item_price                                197428 non-null  int64
 11  total_onshift_dashers                         181166 non-null  float64
 12  total_busy_dashers                            181166 non-null  float64
 13  total_outstanding_orders                      181166 non-null  float64
 14  estimated_order_place_duration                197428 non-null  int64
 15  estimated_store_to_consumer_driving_duration  196902 non-null  float64
dtypes: datetime64[us](2), float64(6), int64(7), str(1)
memory usage: 24.1 MB

In [10]:
df.describe()

,market_id,created_at,actual_delivery_time,store_id,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration
count,196441.000000,197428,197421,197428.000000,196433.000000,197428.000000,197428.000000,197428.000000,197428.000000,197428.000000,181166.000000,181166.000000,181166.000000,197428.000000,196902.000000
mean,2.978706,2026-02-17 08:58:05.324579,2026-02-17 09:02:18.919598,3530.510272,2.882352,3.196391,2682.331402,2.670791,686.218470,1159.588630,44.808093,41.739747,58.050065,308.560179,545.358935
min,1.000000,2026-02-17 00:00:01,2026-02-17 00:00:00,1.000000,1.000000,1.000000,0.000000,1.000000,-86.000000,0.000000,-4.000000,-5.000000,-6.000000,0.000000,0.000000
25%,2.000000,2026-02-17 02:13:43,2026-02-17 02:55:37,1686.000000,1.000000,2.000000,1400.000000,1.000000,299.000000,800.000000,17.000000,15.000000,17.000000,251.000000,382.000000
50%,3.000000,2026-02-17 03:43:20,2026-02-17 04:23:21,3592.000000,3.000000,3.000000,2200.000000,2.000000,595.000000,1095.000000,37.000000,34.000000,41.000000,251.000000,544.000000
75%,4.000000,2026-02-17 19:40:53,2026-02-17 19:56:47,5299.000000,4.000000,4.000000,3395.000000,3.000000,949.000000,1395.000000,65.000000,62.000000,85.000000,446.000000,702.000000
max,6.000000,2026-02-17 23:59:59,2026-02-17 23:59:59,6987.000000,7.000000,411.000000,27100.000000,20.000000,14700.000000,14700.000000,171.000000,154.000000,285.000000,2715.000000,2088.000000
std,1.524867,NaN,NaN,2053.496711,1.503771,2.666546,1823.093688,1.630255,522.038648,558.411377,34.526783,32.145733,52.661830,90.139653,219.352902

Step 4: Create Target Variable

Created new columns as"Delivery_duration"

In [11]:
#Calculate a delivery Time
df['delivery_duration'] = (df['actual_delivery_time'] - df['created_at']).dt.total_seconds()
df[['created_at','actual_delivery_time','delivery_duration']].head()

           created_at actual_delivery_time  delivery_duration
0 2026-02-17 22:24:17  2026-02-17 23:27:16             3779.0
1 2026-02-17 21:49:25  2026-02-17 22:56:29             4024.0
2 2026-02-17 20:39:28  2026-02-17 21:09:09             1781.0
3 2026-02-17 21:21:45  2026-02-17 22:13:00             3075.0
4 2026-02-17 02:40:36  2026-02-17 03:20:26             2390.0

Ex:-
Order placed at: 12:00 AM
Delivered at: 12:30 AM
Difference = 30 minutes

Convert time into second
.dt.total_seconds()
30 minutes = 30 * 60 = 1800 Sec

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 197428 entries, 0 to 197427
Data columns (total 17 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   market_id                                     196441 non-null  float64
 1   created_at                                    197428 non-null  datetime64[us]
 2   actual_delivery_time                          197421 non-null  datetime64[us]
 3   store_id                                      197428 non-null  int64
 4   store_primary_category                        192668 non-null  str
 5   order_protocol                                196433 non-null  float64
 6   total_items                                   197428 non-null  int64
 7   subtotal                                      197428 non-null  int64
 8   num_distinct_items                            197428 non-null  int64
 9   min_item_price                                197428 non-null  int64
 10  max_item_price                                197428 non-null  int64
 11  total_onshift_dashers                         181166 non-null  float64
 12  total_busy_dashers                            181166 non-null  float64
 13  total_outstanding_orders                      181166 non-null  float64
 14  estimated_order_place_duration                197428 non-null  int64
 15  estimated_store_to_consumer_driving_duration  196902 non-null  float64
 16  delivery_duration                             197421 non-null  float64
dtypes: datetime64[us](2), float64(7), int64(7), str(1)
memory usage: 25.6 MB

Step 5: Handle Missing Values

In [13]:
df = df.dropna(subset=["delivery_duration"])
df.fillna(df.median(numeric_only=True),inplace=True)
df.fillna("Unknown",inplace=True)

,market_id,created_at,actual_delivery_time,store_id,store_primary_category,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,delivery_duration
0,1.0,2026-02-17 22:24:17,2026-02-17 23:27:16,1845,american,1.0,4,3441,4,557,1239,33.0,14.0,21.0,446,861.0,3779.0
1,2.0,2026-02-17 21:49:25,2026-02-17 22:56:29,5477,mexican,2.0,1,1900,1,1400,1400,1.0,2.0,2.0,446,690.0,4024.0
2,3.0,2026-02-17 20:39:28,2026-02-17 21:09:09,5477,Unknown,1.0,1,1900,1,1900,1900,1.0,0.0,0.0,446,690.0,1781.0
3,3.0,2026-02-17 21:21:45,2026-02-17 22:13:00,5477,Unknown,1.0,6,6900,5,600,1800,1.0,1.0,2.0,446,289.0,3075.0
4,3.0,2026-02-17 02:40:36,2026-02-17 03:20:26,5477,Unknown,1.0,3,3900,3,1100,1600,6.0,6.0,9.0,446,650.0,2390.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197423,1.0,2026-02-17 00:19:41,2026-02-17 01:24:48,2956,fast,4.0,3,1389,3,345,649,17.0,17.0,23.0,251,331.0,3907.0
197424,1.0,2026-02-17 00:01:59,2026-02-17 00:58:22,2956,fast,4.0,6,3010,4,405,825,12.0,11.0,14.0,251,915.0,3383.0
197425,1.0,2026-02-17 04:46:08,2026-02-17 05:36:16,2956,fast,4.0,5,1836,3,300,399,39.0,41.0,40.0,251,795.0,3008.0
197426,1.0,2026-02-17 18:18:15,2026-02-17 19:23:22,3630,sandwich,1.0,1,1175,1,535,535,7.0,7.0,12.0,446,384.0,3907.0
197427,1.0,2026-02-17 19:24:33,2026-02-17 20:01:41,3630,sandwich,1.0,4,2605,4,425,750,20.0,20.0,23.0,446,134.0,2228.0

Step 6: Create Time Features

In [14]:
df['order_hour'] = df['created_at'].dt.hour
df['order_day'] = df['created_at'].dt.dayofweek

Step 7:Convert Text Column to Numbers

In [15]:
df['store_primary_category'].unique()

<StringArray>
[         'american',           'mexican',           'Unknown',
            'indian',           'italian',          'sandwich',
              'thai',              'cafe',             'salad',
             'pizza',           'chinese',       'singaporean',
            'burger',         'breakfast',     'mediterranean',
          'japanese',             'greek',          'catering',
          'filipino', 'convenience-store',             'other',
            'korean',             'vegan',             'asian',
          'barbecue',              'fast',           'dessert',
          'smoothie',           'seafood',        'vietnamese',
             'cajun',             'steak',    'middle-eastern',
              'soup',        'vegetarian',           'persian',
          'nepalese',             'sushi',    'latin-american',
          'hawaiian',         'chocolate',           'burmese',
           'british',             'pasta',           'alcohol',
           'dim-sum',          'peruvian',           'turkish',
         'malaysian',         'ethiopian',            'afghan',
        'bubble-tea',            'german',            'french',
         'caribbean',       'gluten-free',      'comfort-food',
         'gastropub',         'pakistani',          'moroccan',
           'spanish',          'southern',             'tapas',
           'russian',         'brazilian',          'european',
            'cheese',           'african',         'argentine',
            'kosher',             'irish',          'lebanese',
           'belgian',        'indonesian', 'alcohol-plus-food']
Length: 75, dtype: str

In [16]:
df['store_primary_category'] = df['store_primary_category'].astype('category').cat.codes
df['order_protocol'] = df['order_protocol'].astype('category').cat.codes

In [17]:
df['store_primary_category'].unique()
df['order_protocol'].unique()

array([0, 1, 2, 3, 4, 5, 6], dtype=int8)

Step 8: Selected Features and Target

In [18]:
features = [
    'total_items',
    'subtotal',
    'num_distinct_items',
    'min_item_price',
    'max_item_price',
    'total_onshift_dashers',
    'total_busy_dashers',
    'total_outstanding_orders',
    'estimated_order_place_duration',
    'estimated_store_to_consumer_driving_duration',
    'order_hour',
    'order_day',
    'store_primary_category',
    'order_protocol'
]

X = df[features]
y = df['delivery_duration']

Step 9: Training & Testing Split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training samples:", X_train.shape)
print("Testing samples:", X_test.shape)

NameError: name 'train_test_split' is not defined